import type { LocalizedContentProfile } from "@fardad/types";
import { fardadNavigation } from "./navigation";

export const fardadLocalizedContentProfile: LocalizedContentProfile = {
  id: "fardad-fa",
  version: 2,
  approval: "provisional",
  sourceVersion: "wo-045-two-day-delivery",
  locale: "fa-IR",
  navigation: fardadNavigation,
  shell: {
    skipToContent: "پرش به محتوای اصلی",
    primaryNavigationLabel: "ناوبری اصلی",
    mobileMenuLabel: "منو",
    footerDescription: "فرداد؛ روایتی معاصر از میراث صنایع دستی ایران و تجربه هدیه‌دادن.",
  },
  home: {
    hero: {
      eyebrow: "Persian Heritage Experience",
      titleBeforeBreak: "هنر ایرانی،",
      titleAfterBreak: "در روایتی ماندگار",
      description:
        "فرداد، ویترینی معاصر برای کشف صنایع دستی ایرانی، هدیه‌های سازمانی و ارائه‌هایی است که با دقت و معنا شکل می‌گیرند.",
      primaryAction: "مشاهده محصولات",
      secondaryAction: "دریافت کاتالوگ",
    },
    features: {
      title: "هدیه، با نگاهی سنجیده",
      subtitle: "سه جهت‌گیری پیشنهادی برای تجربه‌ای متناسب، ایرانی و شایسته در فرداد",
      items: [
        {
          title: "متناسب با شأن مخاطب",
          description:
            "توجه به موقعیت، نوع ارتباط و لحن هدیه، برای نزدیک‌شدن به انتخابی سنجیده و محترمانه.",
        },
        {
          title: "هنر ایرانی، ارائه‌ای شایسته",
          description:
            "ترکیب روایت هنر ایرانی با چیدمانی آرام و امروزی، با تمرکز بر فرم، بافت و جزئیات.",
        },
        {
          title: "نگاه به شخصی‌سازی سازمانی",
          description:
            "مسیری پیشنهادی برای هماهنگ‌کردن شیوه ارائه هدیه با مناسبت و هویت سازمانی.",
        },
      ],
    },
    categories: {
      title: "شش مسیر برای کشف هنر ایرانی",
      subtitle: "از رنگ و فلز تا چوب و نقش؛ نگاهی تصویری به زمینه‌های هنری و هدیه‌محور فرداد",
      items: ["فیروزه‌کوبی", "میناکاری", "خاتم‌کاری", "قلمزنی", "هدایای مدیریتی", "پک‌های هدیه"],
    },
  },
  catalog: {
    metadataTitle: "محصولات",
    metadataDescription: "مرور محصولات قابل انتشار فرداد.",
    heading: "محصولات",
    introduction: "مرور محصولات قابل انتشار در مجموعه فرداد.",
    categoryLabel: "دسته‌بندی محصولات",
    categoryDescriptionTemplate: "محصولات دسته‌بندی {categoryName} در فرداد.",
    categoryNavigationLabel: "دسته‌بندی محصولات",
    emptyTitle: "هنوز محصولی برای نمایش وجود ندارد",
    emptyCategoryTitleTemplate: "محصولی در {categoryName} یافت نشد",
    emptyDescription: "به‌محض آماده شدن محصولات قابل انتشار، در این بخش نمایش داده می‌شوند.",
    previousPage: "صفحه قبل",
    nextPage: "صفحه بعد",
    paginationLabel: "صفحه‌بندی محصولات",
    missingImageAltTemplate: "تصویر محصول {productName} در دسترس نیست",
    missingImageMark: "ف",
    missingImageMessage: "تصویر محصول به‌زودی در دسترس خواهد بود",
    loading: "در حال بارگذاری محصولات",
  },
  productDetail: {
    breadcrumbLabel: "مسیر صفحه محصول",
    productsLabel: "محصولات",
    categoryLabel: "دسته‌بندی",
    descriptionHeading: "درباره محصول",
    galleryHeading: "گالری تصاویر",
    missingImageAltTemplate: "تصویر محصول {productName} در دسترس نیست",
    missingImageMark: "ف",
    missingImageMessage: "تصویر محصول در حال حاضر در دسترس نیست",
    loading: "در حال بارگذاری اطلاعات محصول",
    errorTitle: "نمایش اطلاعات محصول با مشکل روبه‌رو شد",
    purchase: {
      addToCart: "افزودن به سبد خرید",
      cartableDescription: "این محصول برای افزودن به سبد خرید آماده است.",
      unavailableDescription: "این محصول در حال حاضر برای خرید آنلاین در دسترس نیست.",
      quantityLabel: "تعداد",
      viewCart: "مشاهده سبد خرید",
      addingToCart: "در حال افزودن به سبد خرید",
      purchaseError: "افزودن محصول به سبد خرید در حال حاضر ممکن نیست. لطفاً دوباره تلاش کنید.",
    },
  },
  cart: {
    metadataTitle: "سبد خرید",
    metadataDescription: "مرور محصولات انتخاب‌شده در سبد خرید فَرداد.",
    heading: "سبد خرید",
    emptyTitle: "سبد خرید شما خالی است",
    emptyDescription: "برای دیدن محصولات قابل انتخاب، به فهرست محصولات بازگردید.",
    continueShopping: "ادامه مشاهده محصولات",
    linesHeading: "محصولات انتخاب‌شده",
    quantityLabel: "تعداد",
    updateQuantity: "به‌روزرسانی تعداد",
    removeLine: "حذف از سبد",
    refreshQuote: "به‌روزرسانی مبلغ",
    subtotalLabel: "جمع سبد",
    quoteFresh: "مبلغ سبد به‌روز است.",
    quoteNeedsRefresh: "مبلغ یکی از محصولات نیاز به به‌روزرسانی دارد.",
    lineUnavailable: "این محصول اکنون در دسترس نیست.",
    lineNeedsRefresh: "اطلاعات این محصول نیاز به به‌روزرسانی دارد.",
    loading: "در حال بارگذاری سبد خرید",
    errorTitle: "نمایش سبد خرید با مشکل روبه‌رو شد",
    errorDescription: "لطفاً دوباره تلاش کنید.",
    retryAction: "تلاش دوباره",
    updatedMessage: "سبد خرید شما به‌روز شد.",
    expiredMessage: "سبد خرید قبلی در دسترس نیست. می‌توانید انتخاب جدیدی انجام دهید.",
    unavailableMessage: "یکی از محصولات دیگر برای خرید در دسترس نیست. سبد خرید به‌روز شد.",
    quantityMessage: "تعداد انتخاب‌شده برای این محصول قابل ثبت نیست.",
    conflictMessage: "سبد خرید به‌روز شد. لطفاً تغییر خود را دوباره بررسی کنید.",
    failureMessage: "انجام این تغییر در حال حاضر ممکن نیست. لطفاً دوباره تلاش کنید.",
    workingMessage: "در حال به‌روزرسانی سبد خرید",
  },
  states: {
    loadingTitle: "در حال بارگذاری",
    loadingDescription: "لطفاً چند لحظه صبر کنید.",
    globalErrorTitle: "خطایی رخ داد",
    productsErrorTitle: "نمایش محصولات با مشکل روبه‌رو شد",
    categoryErrorTitle: "نمایش این دسته‌بندی با مشکل روبه‌رو شد",
    retryDescription: "لطفاً دوباره تلاش کنید.",
    retryAction: "تلاش دوباره",
    notFoundTitle: "صفحه موردنظر پیدا نشد",
    notFoundDescription: "نشانی واردشده در دسترس نیست یا تغییر کرده است.",
    homeAction: "بازگشت به خانه",
  },
  seo: {
    defaultTitle: "فرداد",
    titleTemplate: "%s | فرداد",
    description: "تجربه فرداد برای مرور صنایع دستی ایرانی.",
    robots: { index: true, follow: true },
    openGraphLocale: "fa_IR",
  },
  provisionalFields: ["shell.footerDescription", "home", "catalog", "productDetail", "seo"],
};
